# Generated by Django 3.0.6 on 2020-05-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200518_0849'),
        ('blog', '0002_auto_20200518_1554'),
    ]

    operations = [
    ]
