# Generated by Django 3.0.6 on 2020-05-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
